import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      index: 'src/index.ts',
      client: 'src/api/client.ts',
      analyzer: 'src/core/analyzer.ts',
      generator: 'src/core/generator.ts',
      runGenerator: 'src/core/runGenerator.ts',
      diagramGenerator: 'src/commands/diagramGenerator.ts',
      diagramRender: 'src/commands/diagramRender.ts',
      templates: 'src/templates/index.ts',
      config: 'src/utils/config.ts',
      envLoader: 'src/utils/env-loader.ts',
      fileUtils: 'src/utils/fileUtils.ts',
      logger: 'src/utils/logger.ts',
      mermaidUtils: 'src/utils/mermaidUtils.ts',
      validator: 'src/utils/validator.ts',
      commands: 'src/commands/index.ts',
    },
    format: ['esm'],
    outDir: './dist',
    clean: true,
    dts: false,
    sourcemap: true,
    target: 'es2022',
    platform: 'node',
    splitting: false,
    bundle: false,
    skipNodeModulesBundle: true,
  },
  {
    entry: {
      bin: 'bin/index.ts',
    },
    format: ['esm'],
    outDir: './dist',
    clean: false,
    dts: false,
    sourcemap: false,
    target: 'es2022',
    platform: 'node',
    splitting: false,
    bundle: true,
    skipNodeModulesBundle: true,
    external: [
      '@mermaid-js/mermaid-cli',
      'axios',
      'chalk',
      'commander',
      'dotenv',
      'fs-extra',
      'ora',
    ],
  },
]);
