import { analyzeProject } from '../core/analyzer.js';
import { generateDoc } from '../core/generator.js';
import { diagramRender } from './diagramRender.js';
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import ora from 'ora';

/**
 * Handles diagram commands with validation and retry logic.
 */
export async function handleDiagramCommand(file, options, type) {
    if (file) {
        return diagramRender(file, options, type);
    }

    console.log(chalk.blue(`\n🔍 Analyzing project structure for ${type} diagram...`));

    try {
        const projectData = await analyzeProject(process.cwd());
        const maxRetries = 2; // 1 initial + 1 retry
        let mermaidCode = '';
        let isValid = false;
        let validationError = '';

        const spinner = ora(`Design AI is creating ${type} diagram...`).start();

        for (let i = 0; i < maxRetries; i++) {
            // Generate
            mermaidCode = await generateDoc('diagram', projectData, {
                diagramType: type,
                ai: options.ai
            });

            // Sanitize
            mermaidCode = mermaidCode.replace(/^```mermaid\s*/, '').replace(/^```\s*/, '').replace(/```$/, '').trim();

            // Validate Syntax (Static)
            try {
                validateDiagram(type, mermaidCode);
            } catch (err) {
                validationError = `Static Validation: ${err.message}`;
                if (i < maxRetries - 1) {
                    spinner.text = `Validation failed (${err.message}). Regenerating...`;
                    continue;
                } else {
                    break; // Let it fail at the end
                }
            }

            // Validate by Rendering (Dynamic)
            // We write to a temp file, try to render, and if it fails, we catch it.
            const tempDir = path.resolve(process.cwd(), 'docs', 'temp_diagrams');
            await fs.ensureDir(tempDir);
            const key = Math.random().toString(36).substring(7);
            const tempMmdPath = path.join(tempDir, `${type}_${key}_candidate.mmd`);

            try {
                await fs.writeFile(tempMmdPath, mermaidCode);
                // Attempt render. If this throws, it's invalid.
                // We point output to the same temp dir for the check.
                await diagramRender(tempMmdPath, { output: tempDir }, type);

                // If we got here, it's valid!
                isValid = true;

                // Clean up the temp artifact (png) generated by render check
                const tempPngPath = path.join(tempDir, `${type}_${key}_candidate.png`);
                // We don't need the temp png, just testing if it builds.
                await fs.remove(tempPngPath);
                await fs.remove(tempMmdPath); // Clean mmd too
                await fs.remove(tempDir); // Try to clean dir if empty

                break;
            } catch (err) {
                // Render failed
                validationError = `Render Validation: ${err.message}`;
                // Cleanup temp files if they exist
                await fs.remove(tempMmdPath).catch(() => { });

                if (i < maxRetries - 1) {
                    spinner.text = `Render failed (${err.message}). Regenerating...`;
                    // continue loop
                }
            }
        }

        if (!isValid) {
            spinner.fail(chalk.red('Failed to generate valid diagram after retries.'));
            console.error(chalk.red(`Last Validation Error: ${validationError}`));
            console.error(chalk.dim('\nGenerated Code (Invalid):\n' + mermaidCode));
            // We allow exit here because we exhausted retries
            process.exit(1);
        }

        spinner.succeed(chalk.green('Diagram definition generated and validated'));

        // Save
        const outputDir = options.output ? path.resolve(options.output) : path.resolve(process.cwd(), 'docs', 'diagrams');
        await fs.ensureDir(outputDir);

        const filename = `${type}.mmd`;
        const filePath = path.join(outputDir, filename);

        // NO style injection here anymore

        await fs.writeFile(filePath, mermaidCode);
        console.log(chalk.dim(`\n📄 Saved Mermaid definition: ${filePath}`));

        // Render
        await diagramRender(filePath, options, type);

        const pngPath = path.join(outputDir, `${type}.png`);
        console.log(chalk.cyan(`\nGenerated files:`));
        console.log(chalk.dim(filePath));
        console.log(chalk.green(pngPath));

    } catch (error) {
        console.error(chalk.red(`\n❌ Failed to generate ${type} diagram:`));
        console.error(chalk.red(error.message));
        process.exit(1);
    }
}

function validateDiagram(type, code) {
    // Global restrictions
    // (Removed strict styling checks to allow professional visual themes)


    const cleanCode = code.replace(/%%.*$/gm, '').trim();

    // Type specific validations
    switch (type) {
        case 'activity':
            if (!cleanCode.startsWith('stateDiagram-v2')) throw new Error('Must start with stateDiagram-v2');
            if (code.includes('graph TD') || code.includes('flowchart TD')) throw new Error('Activity diagram cannot use graph/flowchart syntax');
            if (/-->\s*"/.test(code)) throw new Error('Quoted transition target detected');
            if (/"\s*-->/.test(code)) throw new Error('Quoted transition source detected');
            break;

        case 'workflow':
        case 'flowchart':
            if (!cleanCode.startsWith('flowchart')) throw new Error('Must start with flowchart');
            if (/\w+\(/.test(code)) throw new Error('Parentheses in node definition detected (e.g., Node(Label)). Use simple IDs or aliases.');
            break;

        case 'sequence':
            if (!cleanCode.startsWith('sequenceDiagram')) throw new Error('Must start with sequenceDiagram');
            break;

        case 'class':
            if (!cleanCode.startsWith('classDiagram')) throw new Error('Must start with classDiagram');
            break;

        case 'state':
            if (!cleanCode.startsWith('stateDiagram-v2')) throw new Error('Must start with stateDiagram-v2');
            break;

        case 'erd':
        case 'er':
            if (!cleanCode.startsWith('erDiagram')) throw new Error('Must start with erDiagram');
            break;

        case 'usecase':
            // Simulated usecase using graph/flowchart
            if (!cleanCode.startsWith('graph') && !cleanCode.startsWith('flowchart')) throw new Error('Must start with graph or flowchart (Simulated Use Case)');
            break;

        case 'architecture':
        case 'component':
        case 'deployment':
        case 'dfd':
        case 'dfd-level-1':
        case 'dfd-level-2':
        case 'dfd-level-3':
            // Strict graph requirement
            if (!cleanCode.startsWith('graph') && !cleanCode.startsWith('flowchart') && !cleanCode.startsWith('C4Context')) {
                throw new Error('Must start with graph or flowchart');
            }
            break;

        default:
            // Default strictness check for unlisted types if any
            break;
    }
}
